version: "3.9"

services:
  db:
    image: postgres:17
    container_name: task_manager_db

    environment:
      POSTGRES_DB: task_manager_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: bookCollectionDB123

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: task_manager_api

    ports:
      - "8000:8000"

    depends_on:
      - db

    env_file:
      - .env

volumes:
  postgres_data: